### PR TITLE
Feature/azure

### PR DESCRIPTION
**Pull request by andersla**
## Change content and motivation
- Adds a Packer configuration file (build-azure.json) for the Microsoft Azure to the Image builders and updates travis config to include this azure builder.
- Note that this builder only is tested on packer 1.1 so it might be that the packer version used by travis need to be updated also.

## GitHub cross-links 

**Fixes:** 

**Docs**:

### CODE REVIEW

**Comment by mcapuccini** [comment]
@andersla add some better explanation please 🙂

**Comment by mcapuccini** [comment]
@andersla please use Imperial College credentials

**Comment by carmat88** [comment]
@andersla Yeah, I think that I need to enter all the following env variables in Travis for the build to succeed:

- AZ_IMAGE_RESOURCE_GROUP_NAME
- ARM_CLIENT_ID
- ARM_CLIENT_SECRET
- ARM_SUBSCRIPTION_ID
- ARM_TENANT_ID

Could you send them please? Thank you!

**Comment by andersla** [comment]
Closed if favor of #23

**Pull request closed without merging**
