### PR TITLE
Adding travis_wait to avoid timeouts

### PR DESCRIPTION
**Pull request by carmat88**
Adding `travis_wait` to avoid timeouts in azure and openstack

### CODE REVIEW

**Comment by mcapuccini** [comment]
See if this helps, but I think it's time to refactory the code. We need to use travis build stage they work pretty good with the main repo, and we should do the same here. Terraform in Packer causes messy logs. Let's discuss when we meet!

**Comment by carmat88** [comment]
@mcapuccini Yeah, I suppose that's a good idea. However, I am afraid today both our openstack provider and azure are acting whimsical. No such problems in the past days when we merged many other PRs.

**Comment by mcapuccini** [comment]
Yep, I was looking into it, but the log is just impossible to read. My suggestion is to try to make a `0.4.0` with the current settings and then go for a refactory round.

**Comment by carmat88** [comment]
Indeed, I fully agree. Unfortunately a first attempt to release a 0.4.0 failed because of this potential today's instability. Will wait and try again tomorrow whilst also discussing how to revamp the building process.

**Pull request merged**
