### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by carmat88**
Creating README.md for repository Kubenow/image

## Change content and motivation

Adding README.md file to new repository

### CODE REVIEW

**Review by mcapuccini — CHANGES_REQUESTED** [review]
Could you update this a bit? Maybe reuse part of the documentation that you wrote. Also, please include only the latest build status for the image repo only.

**Comment by carmat88** [comment]
@mcapuccini Updated as requested. Please ping me should you have any further comment.

**Comment by carmat88** [comment]
@mcapuccini Further revisions just applied. Please let me know if you like to change anything else. Thanks.

**Comment by mcapuccini** [comment]
@carmat88 nice! Remember to open the issues for future work that we discussed.

**Pull request merged**
