### PR TITLE
Upgrade kube and helm versions and add Heketi and nfs

### PR DESCRIPTION
**Pull request by andersla**
## Change content and motivation
Upgrade kube to 1.6.4
Upgrade helm to 2.4.1
Add Heketi client
Add nfs-client package

## GitHub cross-links 

**Fixes:** 

**Docs**:

### CODE REVIEW

**Comment by mcapuccini** [comment]
@andersla this is going to be tagged as current... we are going to make a release 0.3.1 as soon as you send the PR for heketi

**Comment by mcapuccini** [comment]
@carmat88 it seems like there were some problems with AMI deregistration, can you check it?

**Comment by carmat88** [comment]
@andersla As we discussed with @mcapuccini , we have corrected and improved the way versioning is done (see this [issue](https://github.com/kubenow/KubeNow/issues/202))

Test were successful, so once my [PR](https://github.com/kubenow/image/pull/10) is merged, please pull the new fixes and try to run again the above upgrades. If anything, please let me know. Thanks!

**Comment by carmat88** [comment]
@andersla All good and also quicker than my last test! Think that after this merging we can release 0.3.1. Will wait for Marco's review.

**Review by mcapuccini — APPROVED** [review]
Looking good!

**Comment by mcapuccini** [comment]
@carmat88 let's w8 a couple of days before making a new release, just in case we figure out we want something more. Anders can use the test image that got created in the meanwhile.

**Pull request merged**
