### PR TITLE
Add unattended-upgrades to image 

### PR DESCRIPTION
**Pull request by andersla**
## Change content and motivation
Add unattended-upgrades to Ubuntu image which by default twice a day upgrades with security fixes a running instance
## GitHub cross-links 

**Fixes:** 

**Docs**:

### CODE REVIEW

**Comment by mcapuccini** [comment]
I suggest @carmat88 to take charge of PR review on this repo (as long as he's not the author of the PR). Looks good btw, just need CI to pass.

**Comment by carmat88** [comment]
@andersla I second Marco's comment about the fact that looks good. Though I am puzzled on why OS is failing due to a timeout error. It might be due to a CityCloud glitch. I have restarted only that building to see whether or not it will behave differently today.

**Review by carmat88 — APPROVED** [review]
LGTM, but we need to wait for the CI to be successful on CityCloud which at the moment seems to be unstable.

**Comment by carmat88** [comment]
@andersla CI was eventually successful, so will close and merge. Cheers.

**Pull request merged**
