### PR TITLE
Updating README.md build status for pointing to correct repo

### LINKED ISSUE #222: Image build status points to main repo
The build status in the image repository readme points to the main KubeNow repo CI. It should point to the image CI instead.

### PR DESCRIPTION
**Pull request by carmat88**
## Change content and motivation

As per request in https://github.com/kubenow/KubeNow/issues/222, README.MD building status pointer has been corrected in order to point to Image CI and not to main repo.

Basically only last word of line n°5 has been revised
## GitHub cross-links 

**Fixes:** 
fixes [#222](https://github.com/kubenow/KubeNow/issues/222)

### CODE REVIEW

**Comment by carmat88** [comment]
Hej @mcapuccini . It should be all good. Otherwise, please let me know. Cheers.

**Comment by carmat88** [comment]
@mcapuccini I forgot to follow up for this one as well. It should be all good. Please let me know. Thanks and cheers!

**Review by mcapuccini — CHANGES_REQUESTED** [review]
still a little fix to do :)

**Comment by carmat88** [comment]
@mcapuccini Once #23 is merged with the master, we could proceed with this one as well I think. Thanks.

**Pull request merged**
