### PR TITLE
Support for k8s 1.9.2

### PR DESCRIPTION
**Pull request by jonandernovella**
This PR includes changes regarding the k8s version we use on KubeNow.

### CODE REVIEW

**Comment by carmat88** [comment]
Hello @jonandernovella! Thanks for this upgrading PR. Have you perhaps also tested the created CI image to spawn a cluster and try basic kubernetes operations? In order to see whether everything seems running smoothly?

**Comment by mcapuccini** [comment]
@jonandernovella I suggest using the output image from this CI in the PR that you have sent in conjunction: https://github.com/kubenow/KubeNow/pull/326. If the test goes, we can release a new image, and switch it with the "staging" one.

**Comment by carmat88** [comment]
@jonandernovella Why commenting out the broken container in `travis.yml` ? Wouldn't be better to remove that line entirely, what do you think? Cheers.

**Comment by andersla** [comment]
Now the container is fixed, so It can be uncommented again:)

**Comment by andersla** [comment]
https://github.com/jamesmstone/dockerfiles/issues/2#issuecomment-361113016

**Comment by mcapuccini** [comment]
Let's remove comment and rebuild! Then LGTM.

**Review by carmat88 — APPROVED** [review]
@jonandernovella All good, I'm removing the comment on your behalf. Cheers.

**Comment by andersla** [comment]
Will this image be tagged? something like 0.5b1 or just boldly 0.5 to be changed into 0.5.1 if we find something less appealing with it?

**Comment by mcapuccini** [comment]
`0.5.0b1` sounds good to me. It's ok to be used in the master, since master is not stable :)

**Comment by carmat88** [comment]
@andersla Sounds good to me as well. Feel free to tag it as such, or would you like me to do it?

**Pull request merged**
